version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-api
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: heart-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://heart-api:8000
    depends_on:
      - fastapi
